import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { KeyRound, LogIn } from "lucide-react";

export function LocalLoginPanel() {
  const [identifier, setIdentifier] = useState("");
  const [password, setPassword] = useState("");
  const login = trpc.auth.localLogin.useMutation({ onSuccess: () => window.location.reload() });
  return <div className="mt-6 border-t border-[#e5eee9] pt-6"><div className="flex items-center gap-2"><KeyRound size={15} className="text-[#287767]" /><p className="text-[10px] font-bold uppercase tracking-widest text-[#559385]">Hospital account login</p></div><p className="mt-2 text-[11px] leading-5 text-slate-500">Use the username and password issued by your Super Admin. Your account only opens the role and hospital assigned to it.</p><div className="mt-4 space-y-3"><input value={identifier} onChange={(e) => setIdentifier(e.target.value)} placeholder="Username" autoComplete="username" className="h-11 w-full rounded-xl border border-[#e2ebe6] bg-[#fbfdfc] px-3 text-[12px] outline-none focus:border-[#73b7a6]" /><input value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" type="password" autoComplete="current-password" onKeyDown={(e) => e.key === "Enter" && login.mutate({ identifier, password })} className="h-11 w-full rounded-xl border border-[#e2ebe6] bg-[#fbfdfc] px-3 text-[12px] outline-none focus:border-[#73b7a6]" /><button disabled={!identifier || !password || login.isPending} onClick={() => login.mutate({ identifier, password })} className="flex h-11 w-full items-center justify-center gap-2 rounded-xl border border-[#b9d8cd] bg-[#f1faf6] text-[12px] font-bold text-[#287767] transition hover:bg-[#e5f3ed] disabled:opacity-40"><LogIn size={15} />{login.isPending ? "Signing in…" : "Sign in with username"}</button>{login.error && <p className="rounded-xl bg-[#fff3f0] p-3 text-[10px] text-[#ad5c4c]">{login.error.message}</p>}</div></div>;
}

export function LocalSettingsPage() { const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const change = trpc.auth.localChangePassword.useMutation({ onSuccess: () => { setCurrentPassword(""); setNewPassword(""); } }); return <div className="fade-up space-y-5"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[.14em] text-[#559385]">Account security</p><h1 className="font-display text-[29px] font-extrabold tracking-[-.035em] text-[#173842]">Change password</h1><p className="mt-1 text-[13px] text-slate-500">Update your local account password without changing your assigned role or hospital access.</p></div><section className="card-shadow max-w-xl rounded-[22px] bg-white p-5"><div className="space-y-3"><label className="block"><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-widest text-slate-400">Current password</span><input type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} autoComplete="current-password" className="h-11 w-full rounded-xl border border-[#e2ebe6] px-3 text-[12px] outline-none" /></label><label className="block"><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-widest text-slate-400">New password</span><input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} autoComplete="new-password" placeholder="10+ chars, uppercase, lowercase, number" className="h-11 w-full rounded-xl border border-[#e2ebe6] px-3 text-[12px] outline-none" /></label></div>{change.error && <p className="mt-4 rounded-xl bg-[#fff3f0] p-3 text-[10px] text-[#ad5c4c]">{change.error.message}</p>}{change.isSuccess && <p className="mt-4 rounded-xl bg-[#e5f3ed] p-3 text-[10px] text-[#287767]">Password changed successfully.</p>}<button disabled={!currentPassword || !newPassword || change.isPending} onClick={() => change.mutate({ currentPassword, newPassword })} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#173f47] px-4 py-2.5 text-[11px] font-bold text-white disabled:opacity-40"><KeyRound size={14} />{change.isPending ? "Updating…" : "Update password"}</button></section></div>; }
